/** Auto generated by intelliJ to satisfy userServiceImpl class
 * used in userServiceImpl constructor
 * used to hash the user password if implemented
 **/
public class SecurityService {
    public String md5(String password) {
        return password;
    }
}
