/**
 * This was generated by intellij but is being used because of the userServiceImpl class where it satisfies
 * the userServiceImpl constructor
 **/
public class UserDAO {

    /**
     * This method was generated by intellij and is used to update the user information if implemented
     **/
    public void updateUser(User user) {
    }
}
